.TH "src/Connection.cpp" 3 "Version 0.1" "Hummingbird sql" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Connection.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <xdevapi\&.h>\fP
.br
\fR#include '\&.\&./include/Hummingbird_SQL/Config\&.h'\fP
.br
\fR#include '\&.\&./include/Hummingbird_SQL/Connection\&.h'\fP
.br
\fR#include '\&.\&./include/Hummingbird_SQL/Structures\&.h'\fP
.br
\fR#include 'SqlFunctions\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBHummingBird\fP"
.br
.ti -1c
.RI "namespace \fBHummingBird::Sql\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hummingbird sql from the source code\&.
