.TH "HummingBird::Sql::ColumnInfo" 3 "Version 0.1" "Hummingbird sql" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HummingBird::Sql::ColumnInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Structures\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::string HummingBird::Sql::ColumnInfo::name"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hummingbird sql from the source code\&.
