.TH "HummingBird::Sql::TableInfo" 3 "Version 0.1" "Hummingbird sql" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HummingBird::Sql::TableInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Structures\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "std::string \fBschemaName\fP"
.br
.ti -1c
.RI "std::unordered_map< std::string, \fBColumnInfo\fP > \fBcolumns\fP"
.br
.ti -1c
.RI "std::vector< \fBRow\fP > \fBrows\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::unordered_map<std::string, \fBColumnInfo\fP> HummingBird::Sql::TableInfo::columns"

.SS "std::string HummingBird::Sql::TableInfo::name"

.SS "std::vector<\fBRow\fP> HummingBird::Sql::TableInfo::rows"

.SS "std::string HummingBird::Sql::TableInfo::schemaName"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hummingbird sql from the source code\&.
