.TH "HummingBird::Sql::SchemaInfo" 3 "Version 0.1" "Hummingbird sql" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HummingBird::Sql::SchemaInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Structures\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::optional< \fBTableInfo\fP > \fBgetTable\fP (const std::string &tableName) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "std::unordered_map< std::string, \fBTableInfo\fP > \fBtables\fP = {}"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "std::optional< \fBTableInfo\fP > HummingBird::Sql::SchemaInfo::getTable (const std::string & tableName) const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string HummingBird::Sql::SchemaInfo::name"

.SS "std::unordered_map<std::string, \fBTableInfo\fP> HummingBird::Sql::SchemaInfo::tables = {}"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hummingbird sql from the source code\&.
