.TH "HummingBird::Sql::Local" 3 "Version 0.1" "Hummingbird sql" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HummingBird::Sql::Local
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgetDatabases\fP ()"
.br
.ti -1c
.RI "void \fBgetTables\fP ()"
.br
.ti -1c
.RI "void \fBgetTableColumns\fP ()"
.br
.ti -1c
.RI "void \fBgetTableRows\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void HummingBird::Sql::Local::getDatabases ()"

.SS "void HummingBird::Sql::Local::getTableColumns ()"

.SS "void HummingBird::Sql::Local::getTableRows ()"

.SS "void HummingBird::Sql::Local::getTables ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Hummingbird sql from the source code\&.
