.TH "Settings" 3 "Version 0.1" "Hummingbird sql" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Settings
.SH SYNOPSIS
.br
.PP
.SH "Variable Documentation"
.PP 
.SS "uint32_t Settings::DefaultRowLimit = \fBHUMMINGBIRD_SQL_SETTINGS_DEFAULT_ROW_LIMIT\fP"

.SS "bool Settings::FetchColumnsAndRowsOnConnect = \fBHUMMINGBIRD_SQL_SETTINGS_FETCH_COLUMNS_AND_ROWS_ON_CONNECT\fP"

.SS "bool Settings::FetchTablesOnConnect = \fBHUMMINGBIRD_SQL_SETTINGS_FETCH_TABLES_ON_CONNECT\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Hummingbird sql from the source code\&.
