.TH "include/Hummingbird_SQL/Structures.h" 3 "Version 0.1" "Hummingbird sql" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Hummingbird_SQL/Structures.h
.SH SYNOPSIS
.br
.PP
\fR#include <Hummingbird_SQL/Config\&.h>\fP
.br
\fR#include <Hummingbird_SQL/Connection\&.h>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <unordered_map>\fP
.br
\fR#include <variant>\fP
.br
\fR#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHummingBird::Sql::Row\fP"
.br
.ti -1c
.RI "struct \fBHummingBird::Sql::ColumnInfo\fP"
.br
.ti -1c
.RI "struct \fBHummingBird::Sql::TableInfo\fP"
.br
.ti -1c
.RI "struct \fBHummingBird::Sql::SchemaInfo\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBHummingBird\fP"
.br
.ti -1c
.RI "namespace \fBHummingBird::Sql\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBHummingBird::Sql::ColumnValue\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Hummingbird sql from the source code\&.
