HummingBird::Sql::Connection
bool HummingBird::Sql::Connection::m_isConnected
std::string HummingBird::Sql::Connection::m_currentDatabaseName
std::string HummingBird::Sql::Connection::m_host
std::string HummingBird::Sql::Connection::m_user
std::string HummingBird::Sql::Connection::m_password
uint16_t HummingBird::Sql::Connection::m_port
mysqlx::Session* HummingBird::Sql::Connection::session
std::unordered_map<std::string, std::unique_ptr<SchemaInfo>, case_insensitive_unordered_map::hash, case_insensitive_unordered_map::comp> HummingBird::Sql::Connection::m_schemas
HummingBird::Sql::Connection::Connection()
HummingBird::Sql::Connection::~Connection()
References disconnect, isConnected.
void HummingBird::Sql::Connection::connect(const std::string &hostname, const std::string &username, const std::string &password, const std::string &schemaName, uint16_t port)
Connect to a MySQL database.
Connect to a MySQL database with the given hostname, username, password, schemaName and port. hostname The hostname of the MySQL database username The username of the MySQL database password The password of the MySQL database schemaName The defaultSchemaName of the MySQL database port The port of the MySQL database
References fetchColumns, fetchSchemas, HUMMINGBIRD_SQL_ASSERT, isConnected.
Referenced by main.
void HummingBird::Sql::Connection::disconnect()
Disconnect from the MySQL database.
Disconnect from the MySQL database
References HUMMINGBIRD_SQL_ASSERT, isConnected.
Referenced by ~Connection.
void HummingBird::Sql::Connection::fetchSchemas(const bool fetchTables, const bool fetchColumnsAndRows)
Fetch all schemas, tables, columns and rows.
fetchTables Fetch all tables fetchColumnsAndRows Fetch all columns and rows void
References HummingBird::Sql::Server::getSchemas, HUMMINGBIRD_SQL_SERVER_ERROR_FUNCTION.
Referenced by connect.
void HummingBird::Sql::Connection::fetchTables(SchemaInfo &schema, const bool fetchColumnsAndRows)
Fetch all tables, columns and rows.
schema The schema to fetch the tables from fetchColumnsAndRows Fetch all columns and rows void
References HummingBird::Sql::Server::getTables, HummingBird::Sql::SchemaInfo::tables.
Referenced by fetchTables.
void HummingBird::Sql::Connection::fetchTables(const std::string &schemaName, const bool fetchColumnsAndRows)
Fetch all columns and rows.
schemaName The schemaName to fetch the columns and rows from fetchColumnsAndRows Fetch all columns and rows void
References fetchTables.
void HummingBird::Sql::Connection::fetchColumns(SchemaInfo &schema, TableInfo &table)
Fetch all tables, columns and rows.
schema The schema to fetch the tables from table The table to fetch the columns and rows from void
References HummingBird::Sql::TableInfo::columns, HummingBird::Sql::Server::getTableColumns.
Referenced by connect, fetchColumns, fetchColumns.
void HummingBird::Sql::Connection::fetchColumns(SchemaInfo &schema, const std::string &tableName)
Fetch all columns and rows.
schema The schema to fetch the columns and rows from table The table name to fetch the columns and rows from void
References fetchColumns.
void HummingBird::Sql::Connection::fetchColumns(const std::string &schemaName, const std::string &tableName)
Fetch all columns and rows.
schemaName The schemaName to fetch the columns and rows from tableName The tableName to fetch the columns and rows from void
References fetchColumns.
void HummingBird::Sql::Connection::fetchRows(SchemaInfo &schema, TableInfo &table)
Fetch all rows.
schema The schema to fetch the rows from table The table to fetch the rows from void
References HummingBird::Sql::Server::getTableRows, HummingBird::Sql::TableInfo::rows.
Referenced by fetchRows, fetchRows.
void HummingBird::Sql::Connection::fetchRows(SchemaInfo &schema, const std::string &tableName)
Fetch all rows.
schemaName The schemaName to fetch the rows from tableName The tableName to fetch the rows from void
References fetchRows.
void HummingBird::Sql::Connection::fetchRows(const std::string &schemaNames, const std::string &tableName)
Fetch all rows.
schemaName The schemaName to fetch the rows from tableName The tableName to fetch the rows from void
References fetchRows.
const SchemaInfo & HummingBird::Sql::Connection::getSchema(const std::string &schemaName)
Get an schema by name.
schemaName The name of the schema SchemaInfo The schema
References HUMMINGBIRD_SQL_SERVER_ERROR_FUNCTION.
const TableInfo & HummingBird::Sql::Connection::getTable(SchemaInfo &schema, const std::string &tableName)
Get an table by name.
schema The schema to get the table from tableName The name of the table TableInfo The table
References HUMMINGBIRD_SQL_SERVER_ERROR_FUNCTION.
const TableInfo & HummingBird::Sql::Connection::getTable(const std::string &schema, const std::string &tableName)
Get an table by name.
schemaName The schemaName to get the table from tableName The name of the table TableInfo The table
bool HummingBird::Sql::Connection::isConnected() const
Get connection status.
bool True if connected
Referenced by connect, disconnect, HummingBird::Sql::Server::getSchemas, HummingBird::Sql::Server::getTableColumns, HummingBird::Sql::Server::getTableRows, HummingBird::Sql::Server::getTables, ~Connection.
mysqlx::Session & HummingBird::Sql::Connection::getSession() const
Get the current session ptr.
Session ptr The session ptr
Referenced by HummingBird::Sql::Server::getSchemas, HummingBird::Sql::Server::getTableColumns, HummingBird::Sql::Server::getTableRows, HummingBird::Sql::Server::getTables.
SchemaInfo * HummingBird::Sql::Connection::getSchemaPtr(const std::string &schemaName)
Get an schema by name.
schemaName The name of the schema SchemaInfo ptr The schema nullptr if the schema is not found
TableInfo * HummingBird::Sql::Connection::getTablePtr(SchemaInfo &schema, const std::string &tableName)
Get an table by name.
schema The schema to get the table from tableName The name of the table TableInfo ptr The table nullptr if the table is not found