HummingBird::Sql::Server
std::unordered_map< std::string, std::unique_ptr< SchemaInfo >, case_insensitive_unordered_map::hash, case_insensitive_unordered_map::comp > HummingBird::Sql::Server::getSchemas(const Connection &connection, const bool getTables, const bool getColumnsAndRows=false)
References HummingBird::Sql::Connection::getSession, getTables, HUMMINGBIRD_SQL_ASSERT, HUMMINGBIRD_SQL_SERVER_LOG_FUNCTION, HUMMINGBIRD_SQL_SERVER_TRACE_FUNCTION, HummingBird::Sql::Connection::isConnected.
Referenced by HummingBird::Sql::Connection::fetchSchemas.
std::unordered_map< std::string, TableInfo > HummingBird::Sql::Server::getTables(const Connection &connection, const SchemaInfo &databaseInfo, const bool getColumnsAndRows=false)
References HummingBird::Sql::TableInfo::columns, HummingBird::Sql::Connection::getSession, getTableColumns, getTableRows, HUMMINGBIRD_SQL_ASSERT, HUMMINGBIRD_SQL_SERVER_LOG_FUNCTION, HUMMINGBIRD_SQL_SERVER_TRACE_FUNCTION, HummingBird::Sql::Connection::isConnected, HummingBird::Sql::TableInfo::name, HummingBird::Sql::SchemaInfo::name, HummingBird::Sql::TableInfo::rows, HummingBird::Sql::TableInfo::schemaName.
Referenced by HummingBird::Sql::Connection::fetchTables, getSchemas.
std::unordered_map< std::string, ColumnInfo > HummingBird::Sql::Server::getTableColumns(const Connection &connection, const SchemaInfo &databaseInfo, const TableInfo &tableInfo)
References HummingBird::Sql::Connection::getSession, HUMMINGBIRD_SQL_ASSERT, HUMMINGBIRD_SQL_SERVER_TRACE_FUNCTION, HummingBird::Sql::Connection::isConnected, HummingBird::Sql::ColumnInfo::name, HummingBird::Sql::TableInfo::name, HummingBird::Sql::SchemaInfo::name.
Referenced by HummingBird::Sql::Connection::fetchColumns, getTables.
std::vector< Row > HummingBird::Sql::Server::getTableRows(const Connection &connection, const SchemaInfo &databaseInfo, const TableInfo &tableInfo, int limit=Settings::Limits.DefaultRowLimit)
References HummingBird::Sql::Row::addColumn, HummingBird::Sql::TableInfo::columns, HummingBird::Sql::Connection::getSession, HUMMINGBIRD_SQL_ASSERT, HUMMINGBIRD_SQL_SERVER_ERROR_FUNCTION, HUMMINGBIRD_SQL_SERVER_LOG_FUNCTION, HUMMINGBIRD_SQL_SERVER_TRACE_FUNCTION, HummingBird::Sql::Connection::isConnected, HummingBird::Sql::TableInfo::name, HummingBird::Sql::SchemaInfo::name.
Referenced by HummingBird::Sql::Connection::fetchRows, getTables.